[features]
seeds = false
skip-lint = false
[programs.localnet]
easycrypto_sdk = "H4mRYtWnvQkQgbM9iw4TxGZxeqfHMKCCdc2eehbCua1f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/congdm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
